@startuml library
left to right direction

actor Admin
actor Reader

rectangle library{
usecase "Manage Books" as UC_ManageBook
usecase "View Available Books" as UC_ViewAvailableBooks
usecase "Advanced Search" as UC_AdvancedSearch
usecase "Search a Book" as UC_SearchBook
usecase "Display Available Books in Console" as UC_DisplayBooksConsole
usecase "Borrow a Book" as UC_BorrowBook
usecase "Manage Authors" as UC_ManageAuthors
usecase "Manage Readers" as UC_ManageReaders
}

UC_ViewAvailableBooks  <.. UC_SearchBook : <<extend>>
UC_ManageBook <.. UC_AdvancedSearch : <<extend>>
UC_ManageBook <.. UC_DisplayBooksConsole : <<extend>>
UC_ManageBook <.. UC_BorrowBook: <<extend>>

Admin -- UC_ManageBook : "Manage"
Admin -- UC_ManageAuthors : "Manage"
Admin -- UC_ManageReaders : "Manage"

Reader -- UC_ViewAvailableBooks : "View"
@enduml